name: Lint, format and test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          make install
          make install-dev

      - name: Lint
        run: make lint

      - name: Format
        run: make ARGS=--check fmt

      - name: Test
        run: make test
