name: Export organisation data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1" # 04:00 UTC on Monday

env:
  SALESFORCE_CONNECTED_APP_ID: ${{ secrets.SALESFORCE_CONNECTED_APP_ID }}
  SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
  SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
  SALESFORCE_SECURITY_TOKEN: ${{ secrets.SALESFORCE_SECURITY_TOKEN }}
  SALESFORCE_DOMAIN: ${{ secrets.SALESFORCE_DOMAIN }}

jobs:
  export-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install dependencies
        run: |
          make install

      - name: Export organisation data
        id: export
        run: |
          EXPORT_OUTPUT="$(make)"
          echo "$EXPORT_OUTPUT"
          if [[ "$EXPORT_OUTPUT" == *"Missing org data"* ]]; then
            echo "MISSING_DATA=true" >> $GITHUB_ENV
          fi

      - name: Check for changes
        id: changes
        run: |
          echo "CHANGE_COUNT=$(git status --porcelain | wc -l)" >> $GITHUB_ENV

      - name: Commit files
        if: env.CHANGE_COUNT != 0
        run: |
          EXPORT_DATE=`date '+%Y-%m-%d (%H:%M)'`
          git config --local user.email "action@github.com"
          git config --local user.name "SRE Internal"
          git add -A
          git commit -m "chore: organisation export for $EXPORT_DATE" -a
          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:main

      - name: Slack message if missing data
        if: env.MISSING_DATA == 'true'
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":warning: Missing organisation data: <https://github.com/cds-snc/gc-organisations/actions/workflows/export.yml|Export organisation data>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.EXPORT_SLACK_WEBHOOK }}

      - name: Slack message on failure
        if: failure()
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Failed to export organisations: <https://github.com/cds-snc/gc-organisations/actions/workflows/export.yml|Export organisation data>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.EXPORT_SLACK_WEBHOOK }}
