name: Shellcheck
on:
  push:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
    - name: Shellcheck
      run: |
        .github/workflows/scripts/run-shellcheck.sh



